apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi:local
          ports:
            - containerPort: 80
          command: ["uvicorn"]
          args: ["app.main:app", "--host", "127.0.0.1", "--port", "5000"]
