apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fastapi-rollout
  labels:
    app: fastapi
spec:
  replicas: 6
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fastapi
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      steps:
        - setWeight: 20
        - pause: {duration: 30s}
        - setWeight: 50
        - pause: {duration: 60s}
        - setWeight: 100
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi:0.1
          ports:
            - containerPort: 80
          command: ["uvicorn"]
          args: ["app.main:app", "--host", "0.0.0.0", "--port", "5000"]
